/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bugmanagingapp;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;

public class App {
    public String getGreeting() {
        listReports();
        return "Hello World!";

    }

    public void listReports() {      
        HttpClient httpClient = HttpClient.newHttpClient();  
        HttpRequest request = HttpRequest.newBuilder(URI.create(Utils.USER_API)).GET().build();  
        try {  
            HttpResponse<InputStream> response = httpClient.send(request, HttpResponse.BodyHandlers.ofInputStream());  
    
            int statusCode = response.statusCode();  
            System.out.println("HTTP status: " + statusCode);  
    
            System.out.println("Reports returned in request: ");  
            List<Report> reports = Utils.toList(response.body());  
            reports.forEach(System.out::println);  
    
            System.out.println("Headers:");  
            response.headers().map().forEach((header, value) -> System.out.println(header + " = " + String.join(", ", value)));  
        }  
        catch (IOException | InterruptedException e) {  
            throw new RuntimeException(e);  
        }  
}
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
    }
}
