/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bugmanagingapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void listReportDoesNotThrow() {
        App classUnderTest = new App();
        assertDoesNotThrow(() -> classUnderTest.listReports());
    }
}
